using Pokemod.Content.NPCs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Terraria;

namespace Pokemod.Common.Systems
{
    internal class PokemonTypeChart
    {
        public static Dictionary<String, Dictionary<String, byte>> typeChart = new() {
            // First type is the defender, second is attacker.
            // 0 = immunity
            // 1 = ineffective
            // 2 = neutral
            // 4 = super effective
            { "Normal", new() {
                {"Normal",      2},
                {"Fire",        2},
                {"Water",       2},
                {"Electric",    2},
                {"Grass",       2},
                {"Ice",         2},
                {"Fighting",    4},
                {"Poison",      2},
                {"Ground",      2},
                {"Flying",      2},
                {"Psychic",     2},
                {"Bug",         2},
                {"Rock",        2},
                {"Ghost",       0},
                {"Dragon",      2},
                {"Dark",        2},
                {"Steel",       2},
                {"Fairy",       2},
            } },
            { "Fire", new() {
                {"Normal",      2},
                {"Fire",        1},
                {"Water",       4},
                {"Electric",    2},
                {"Grass",       1},
                {"Ice",         1},
                {"Fighting",    2},
                {"Poison",      2},
                {"Ground",      4},
                {"Flying",      2},
                {"Psychic",     2},
                {"Bug",         1},
                {"Rock",        4},
                {"Ghost",       2},
                {"Dragon",      2},
                {"Dark",        2},
                {"Steel",       1},
                {"Fairy",       1},
            } },
            { "Water", new() {
                {"Normal",      2},
                {"Fire",        1},
                {"Water",       1},
                {"Electric",    4},
                {"Grass",       4},
                {"Ice",         1},
                {"Fighting",    2},
                {"Poison",      2},
                {"Ground",      2},
                {"Flying",      2},
                {"Psychic",     2},
                {"Bug",         2},
                {"Rock",        2},
                {"Ghost",       2},
                {"Dragon",      2},
                {"Dark",        2},
                {"Steel",       1},
                {"Fairy",       2},
            } },
            { "Electric", new() {
                {"Normal",      2},
                {"Fire",        2},
                {"Water",       2},
                {"Electric",    1},
                {"Grass",       2},
                {"Ice",         2},
                {"Fighting",    2},
                {"Poison",      2},
                {"Ground",      4},
                {"Flying",      1},
                {"Psychic",     2},
                {"Bug",         2},
                {"Rock",        2},
                {"Ghost",       2},
                {"Dragon",      2},
                {"Dark",        2},
                {"Steel",       1},
                {"Fairy",       2},
            } },
            { "Grass", new() {
                {"Normal",      2},
                {"Fire",        4},
                {"Water",       1},
                {"Electric",    1},
                {"Grass",       1},
                {"Ice",         4},
                {"Fighting",    2},
                {"Poison",      4},
                {"Ground",      1},
                {"Flying",      4},
                {"Psychic",     2},
                {"Bug",         4},
                {"Rock",        2},
                {"Ghost",       2},
                {"Dragon",      2},
                {"Dark",        2},
                {"Steel",       2},
                {"Fairy",       2},
            } },
            { "Ice", new() {
                {"Normal",      2},
                {"Fire",        4},
                {"Water",       2},
                {"Electric",    2},
                {"Grass",       2},
                {"Ice",         1},
                {"Fighting",    4},
                {"Poison",      2},
                {"Ground",      2},
                {"Flying",      2},
                {"Psychic",     2},
                {"Bug",         2},
                {"Rock",        4},
                {"Ghost",       2},
                {"Dragon",      2},
                {"Dark",        2},
                {"Steel",       4},
                {"Fairy",       2},
            } },
            { "Fighting", new() {
                {"Normal",      2},
                {"Fire",        2},
                {"Water",       2},
                {"Electric",    2},
                {"Grass",       2},
                {"Ice",         2},
                {"Fighting",    2},
                {"Poison",      2},
                {"Ground",      2},
                {"Flying",      4},
                {"Psychic",     4},
                {"Bug",         1},
                {"Rock",        1},
                {"Ghost",       2},
                {"Dragon",      2},
                {"Dark",        1},
                {"Steel",       2},
                {"Fairy",       4},
            } },
            { "Poison", new() {
                {"Normal",      2},
                {"Fire",        2},
                {"Water",       2},
                {"Electric",    2},
                {"Grass",       1},
                {"Ice",         2},
                {"Fighting",    1},
                {"Poison",      1},
                {"Ground",      4},
                {"Flying",      2},
                {"Psychic",     4},
                {"Bug",         1},
                {"Rock",        2},
                {"Ghost",       2},
                {"Dragon",      2},
                {"Dark",        2},
                {"Steel",       2},
                {"Fairy",       1},
            } },
            { "Ground", new() {
                {"Normal",      2},
                {"Fire",        2},
                {"Water",       4},
                {"Electric",    0},
                {"Grass",       4},
                {"Ice",         4},
                {"Fighting",    2},
                {"Poison",      1},
                {"Ground",      2},
                {"Flying",      2},
                {"Psychic",     2},
                {"Bug",         2},
                {"Rock",        1},
                {"Ghost",       2},
                {"Dragon",      2},
                {"Dark",        2},
                {"Steel",       2},
                {"Fairy",       2},
            } },
            { "Flying", new() {
                {"Normal",      2},
                {"Fire",        2},
                {"Water",       2},
                {"Electric",    4},
                {"Grass",       1},
                {"Ice",         4},
                {"Fighting",    1},
                {"Poison",      2},
                {"Ground",      0},
                {"Flying",      2},
                {"Psychic",     2},
                {"Bug",         1},
                {"Rock",        4},
                {"Ghost",       2},
                {"Dragon",      2},
                {"Dark",        2},
                {"Steel",       2},
                {"Fairy",       2},
            } },
            { "Psychic", new() {
                {"Normal",      2},
                {"Fire",        2},
                {"Water",       2},
                {"Electric",    2},
                {"Grass",       2},
                {"Ice",         2},
                {"Fighting",    1},
                {"Poison",      2},
                {"Ground",      2},
                {"Flying",      2},
                {"Psychic",     1},
                {"Bug",         4},
                {"Rock",        2},
                {"Ghost",       4},
                {"Dragon",      2},
                {"Dark",        4},
                {"Steel",       2},
                {"Fairy",       2},
            } },
            { "Bug", new() {
                {"Normal",      2},
                {"Fire",        4},
                {"Water",       2},
                {"Electric",    2},
                {"Grass",       1},
                {"Ice",         2},
                {"Fighting",    1},
                {"Poison",      2},
                {"Ground",      1},
                {"Flying",      4},
                {"Psychic",     2},
                {"Bug",         2},
                {"Rock",        4},
                {"Ghost",       2},
                {"Dragon",      2},
                {"Dark",        2},
                {"Steel",       2},
                {"Fairy",       2},
            } },
            { "Rock", new() {
                {"Normal",      1},
                {"Fire",        1},
                {"Water",       4},
                {"Electric",    2},
                {"Grass",       4},
                {"Ice",         2},
                {"Fighting",    4},
                {"Poison",      1},
                {"Ground",      4},
                {"Flying",      1},
                {"Psychic",     2},
                {"Bug",         2},
                {"Rock",        2},
                {"Ghost",       2},
                {"Dragon",      2},
                {"Dark",        2},
                {"Steel",       4},
                {"Fairy",       2},
            } },
            { "Ghost", new() {
                {"Normal",      0},
                {"Fire",        2},
                {"Water",       2},
                {"Electric",    2},
                {"Grass",       2},
                {"Ice",         2},
                {"Fighting",    0},
                {"Poison",      1},
                {"Ground",      2},
                {"Flying",      2},
                {"Psychic",     2},
                {"Bug",         1},
                {"Rock",        2},
                {"Ghost",       4},
                {"Dragon",      2},
                {"Dark",        4},
                {"Steel",       2},
                {"Fairy",       2},
            } },
            { "Dragon", new() {
                {"Normal",      2},
                {"Fire",        1},
                {"Water",       1},
                {"Electric",    1},
                {"Grass",       1},
                {"Ice",         4},
                {"Fighting",    2},
                {"Poison",      2},
                {"Ground",      2},
                {"Flying",      2},
                {"Psychic",     2},
                {"Bug",         2},
                {"Rock",        2},
                {"Ghost",       2},
                {"Dragon",      4},
                {"Dark",        2},
                {"Steel",       2},
                {"Fairy",       4},
            } },
            { "Dark", new() {
                {"Normal",      2},
                {"Fire",        2},
                {"Water",       2},
                {"Electric",    2},
                {"Grass",       2},
                {"Ice",         2},
                {"Fighting",    4},
                {"Poison",      2},
                {"Ground",      2},
                {"Flying",      2},
                {"Psychic",     0},
                {"Bug",         4},
                {"Rock",        2},
                {"Ghost",       1},
                {"Dragon",      2},
                {"Dark",        1},
                {"Steel",       2},
                {"Fairy",       4},
            } },
            { "Steel", new() {
                {"Normal",      1},
                {"Fire",        4},
                {"Water",       2},
                {"Electric",    2},
                {"Grass",       1},
                {"Ice",         1},
                {"Fighting",    4},
                {"Poison",      0},
                {"Ground",      4},
                {"Flying",      1},
                {"Psychic",     1},
                {"Bug",         1},
                {"Rock",        1},
                {"Ghost",       2},
                {"Dragon",      1},
                {"Dark",        2},
                {"Steel",       1},
                {"Fairy",       1},
            } },
            { "Fairy", new() {
                {"Normal",      2},
                {"Fire",        2},
                {"Water",       2},
                {"Electric",    2},
                {"Grass",       2},
                {"Ice",         2},
                {"Fighting",    1},
                {"Poison",      4},
                {"Ground",      2},
                {"Flying",      2},
                {"Psychic",     2},
                {"Bug",         1},
                {"Rock",        2},
                {"Ghost",       2},
                {"Dragon",      0},
                {"Dark",        1},
                {"Steel",       4},
                {"Fairy",       2},
            } },
        };

        public static float GetTypeEffectiveness(int attackType, int defendingType1, int defendingType2 = -1)
        {
            if (!(attackType > -1 && attackType < typeChart.Count) || !(defendingType1 > -1 && defendingType1 < typeChart.Count) || !(defendingType2 < typeChart.Count))
            {
                Main.NewText("TypeChart - Invalid Type: " + attackType + "," + defendingType1 + "," + defendingType2 + " (within: " + typeChart.Count + ")");
                return 1f;
            }

            float effectiveness = 1;
            string attack = ((TypeIndex)attackType).ToString();
            string defence1 = ((TypeIndex)defendingType1).ToString();
            byte modifier1 = typeChart[defence1][attack];

            byte modifier2 = 2;
            if (defendingType2 > -1){
                string defence2 = ((TypeIndex)defendingType2).ToString();
                modifier2 = typeChart[defence2][attack];
            }

            effectiveness *= (modifier1 / 2f) * (modifier2 / 2f);

            // Minimum effectiveness capped at 0.25 as true immunities might not function well in Terraria.
            effectiveness = Math.Clamp(effectiveness, 0.25f, 4f);

            return effectiveness;
        }
    }
}

